### ISSUE TITLE
Do we really need NullURL?

### ISSUE THREAD

**Issue by twingly-mob** [twingly/twingly-url#44]
Perhaps we can make an "empty" instance of Twingly::URL?

Would for example help us with `respond_to?` and such things.

**Comment by dentarg** [comment]
Wouldn't we need kinda complicated logic without NullURL? Instead of returning `NullURL.new`, I guess we would do something like `@valid = false`... but uhm, I think `false` should be the default (or should it be `nil`?), before we have parsed anything. So then we need to set it to true somewhere. And should you be able to do change the valid status later for a parsed URL, `url.valid = false`? I like that it's "immutable" now (always `false` for NullURL and always `true` for URL).

**Comment by walro** [comment]
I don't remember the reason to why the issue was created, can we make an example of how

> Would for example help us with respond_to? and such things.

would become easier? Currently I don't mind `NullURL`.

**Comment by dentarg** [comment]
@walro yeah let's ping @twingly-mob and ask for clarification here

**Comment by dentarg** [comment]
;-)

**Comment by dentarg** [comment]
I would like to close this one, I also don't mind NullURL.

**Comment by walro** [comment]
+1

**Comment by dentarg** [comment]
We can always re-open if other opinions surface.
